[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "altan"
version = "0.1.0"
description = "Python client for the Altan Actions API"
readme = "README.md"
authors = [
    {name = "Altan Team", email = "support@altan.io"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dependencies = [
    "requests>=2.25.0",
]

[project.optional-dependencies]
async = [
    "httpx>=0.22.0",
]
dev = [
    "pytest>=6.0.0",
    "pytest-cov>=2.12.0",
    "black>=21.5b2",
    "isort>=5.9.1",
    "mypy>=0.812",
    "flake8>=3.9.2",
    "httpx>=0.22.0",
]

[project.urls]
Homepage = "https://github.com/altan/altan-python"
Documentation = "https://altan.io/docs"
Repository = "https://github.com/altan/altan-python.git"
Issues = "https://github.com/altan/altan-python/issues" 