/**
 * ⚠️ LEGACY COMPATIBILITY LAYER ⚠️
 * 
 * This file has been refactored into a modular structure in ./bases/
 * This compatibility layer exists for backwards compatibility only.
 * 
 * ⚠️ DO NOT EDIT THIS FILE - IT WILL BE REMOVED IN A FUTURE VERSION
 * 
 * Please update your imports to use the new modular structure:
 * 
 * OLD (DEPRECATED):
 *   import { fetchTables } from 'src/redux/slices/bases'
 * 
 * NEW (RECOMMENDED):
 *   import { fetchTables } from 'src/redux/slices/bases/'
 *                                                         ^ Add trailing slash
 * 
 * Or use explicit paths for better tree-shaking:
 *   import { fetchTables } from 'src/redux/slices/bases/thunks'
 *   import { selectTablesByBaseId } from 'src/redux/slices/bases/selectors'
 * 
 * See ./bases/README.md for complete documentation.
 */

// Direct re-exports from the new modular structure
// These avoid circular dependencies by importing directly from subdirectories

import basesReducer from './bases/combineReducers';

// Export default reducer
export default basesReducer;

// Re-export everything from bases index (named exports only, not default)
export {
  // Actions
  setLoading,
  setError,
  stopLoading,
  addBase,
  updateBase,
  deleteBase,
  setSchemasLoading,
  setSchemas,
  setSchemasError,
  setTables,
  addTable,
  updateTable,
  deleteTable,
  setColumns,
  addField,
  updateField,
  deleteField,
  setTableRecordsLoading,
  setTableRecords,
  addTableRecord,
  updateTableRecord,
  deleteTableRecord,
  setTableRecordsState,
  clearTableRecords,
  integrateRealTimeUpdates,
  clearRealTimeUpdateFlags,
  setUserCacheLoading,
  setUserCache,
  setUserCacheError,
  clearUserCache,
  setBucketCacheLoading,
  setBucketCache,
  setBucketCacheError,
  clearBucketCache,
  addBucketToCache,
  removeBucketFromCache,
  updateBucketInCache,
  // Thunks
  createSchema,
  deleteSchema,
  fetchTables,
  createTable,
  updateTableById,
  deleteTableById,
  fetchTablePolicies,
  fetchColumns,
  createField,
  updateFieldById,
  deleteFieldById,
  getTableRecord,
  getTableRecordCount,
  loadTableRecords,
  loadAllTableRecords,
  queryTableRecords,
  createTableRecord,
  updateTableRecordById,
  deleteTableRecordById,
  preloadUsersForBase,
  deleteUserFromBase,
  preloadBucketsForBase,
  importCSVToTable,
  exportDatabaseToCSV,
  exportDatabaseToSQL,
  handleRealTimeUpdates,
  // Selectors
  selectBasesState,
  selectBases,
  selectBasesLoading,
  selectBasesError,
  selectBasesInitialized,
  selectTablesState,
  selectTablesByBaseId,
  selectAllTablesByBaseId,
  selectTableById,
  selectFieldsByTableId,
  selectRecords,
  selectRecordsState,
  selectTableRecords,
  selectTableRecordsTotal,
  selectTableRecordsState,
  selectIsTableRecordsLoading,
  selectTableRecordById,
  selectTablePaginationInfo,
  selectTableTotalRecords,
  selectUserCache,
  selectUserCacheState,
  selectUserCacheForBase,
  selectUserById,
  createUserDisplayValueSelector,
  selectBucketCache,
  selectBucketCacheState,
  selectBucketCacheForBase,
  selectBucketById,
  createRecordPrimaryValueSelector,
  // Utilities
  handleThunkError,
  deduplicateRecords,
  isTextSearchableField,
  hasCreatedAtField,
} from './bases/index';

// Re-export types
export type {
  PgMetaColumn,
  PgMetaTable,
  BaseField,
  BaseTable,
  BaseSchema,
  BaseRecord,
  RLSPolicy,
  BaseUser,
  BaseBucket,
  CloudInstance,
  RecordMetadata,
  RecordsState,
  SchemaState,
  TablesState,
  RecordsData,
  CacheState,
  BasesState,
  FetchTablesOptions,
  LoadTableRecordsOptions,
  QueryParams,
  FieldData,
  RealTimeUpdates,
} from './bases/types';
