/**
 * ⚠️ LEGACY COMPATIBILITY LAYER ⚠️
 * 
 * This file has been refactored into a modular structure in ./cloud/
 * This compatibility layer exists for backwards compatibility only.
 * 
 * ⚠️ DO NOT EDIT THIS FILE - IT WILL BE REMOVED IN A FUTURE VERSION
 * 
 * Please update your imports to use the new modular structure:
 * 
 * OLD (DEPRECATED):
 *   import { fetchCloud } from 'src/redux/slices/cloud'
 * 
 * NEW (RECOMMENDED):
 *   import { fetchCloud } from 'src/redux/slices/cloud/'
 *                                                        ^ Add trailing slash
 * 
 * Or use explicit paths for better tree-shaking:
 *   import { fetchCloud } from 'src/redux/slices/cloud/thunks'
 *   import { selectCloudById } from 'src/redux/slices/cloud/selectors'
 * 
 * See ./cloud/README.md for complete documentation.
 */

// Direct imports to avoid circular dependencies
import cloudReducer from './cloud/combineReducers';

// Export default reducer
export default cloudReducer;

// Re-export everything from cloud index (named exports only)
export {
  // Actions
  setLoading,
  setError,
  setCloud,
  updateCloud,
  removeCloud,
  setTableLoading,
  setTableRecords,
  addRecord,
  updateRecord,
  removeRecord,
  setUsers,
  setBuckets,
  setBucketCacheLoading,
  setBucketCacheError,
  addBucket,
  updateBucket,
  removeBucket,
  setQuickFilter,
  setSearching,
  setSearchResults,
  clearSearchResults,
  // Thunks
  fetchCloud,
  createTable,
  deleteTable,
  fetchRecords,
  createRecord,
  updateRecordById,
  deleteRecord,
  fetchUsers,
  deleteUser,
  fetchBuckets,
  searchTableRecords,
  // Selectors
  selectCloudById,
  selectTablesByCloudId,
  selectTableById,
  selectTableFields,
  selectTableRecords,
  selectTableLoading,
  selectTableState,
  selectUsersForCloud,
  selectUserById,
  selectBucketsForCloud,
  selectBucketById,
  selectBucketCacheState,
  selectQuickFilter,
  selectSearching,
  selectSearchResults,
  // Utilities
  normalizeTableId,
  findTableById,
  isTextSearchableField,
} from './cloud/index';

// Re-export types
export type {
  CloudInstance,
  CloudTable,
  CloudRecord,
  CloudUser,
  CloudBucket,
  CloudField,
  TableState,
  SearchResult,
  CacheState,
  DatabaseNavigation,
} from './cloud/types';

// Additional backwards-compatible selector exports
export { selectCloudById as selectCloudState } from './cloud/selectors/clouds.selectors';
