export const verticalOptions = [
  { value: 'saas', label: 'SaaS' },
  { value: 'ecommerce', label: 'E-commerce' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'finance', label: 'Financial Services' },
  { value: 'education', label: 'Education' },
  { value: 'real_estate', label: 'Real Estate' },
  { value: 'retail', label: 'Retail' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'hospitality', label: 'Hospitality & Travel' },
  { value: 'food_service', label: 'Food Service & Restaurants' },
  { value: 'non_profit', label: 'Non-profit & NGO' },
  { value: 'government', label: 'Government' },
  { value: 'legal', label: 'Legal' },
  { value: 'media', label: 'Media & Entertainment' },
  { value: 'telecom', label: 'Telecommunications' },
  { value: 'energy', label: 'Energy & Utilities' },
  { value: 'consulting', label: 'Consulting & Professional Services' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'security', label: 'Security & Defense' },
  { value: 'logistics', label: 'Logistics & Transportation' },
  { value: 'gaming', label: 'Gaming & Interactive Media' },
];

export const featureOptions = [
  { value: 'ai_powered', label: 'AI-Powered' },
  { value: 'mobile_friendly', label: 'Mobile-Friendly' },
  { value: 'api_integrations', label: 'API Integrations' },
  { value: 'customizable', label: 'Highly Customizable' },
  { value: 'white_label', label: 'White-Label Ready' },
  { value: 'data_viz', label: 'Data Visualization' },
  { value: 'multi_user', label: 'Multi-User Support' },
  { value: 'notifications', label: 'Notification System' },
  { value: 'file_mgmt', label: 'File Management' },
  { value: 'search', label: 'Advanced Search' },
  { value: 'analytics', label: 'Built-in Analytics' },
  { value: 'export', label: 'Export Capabilities' },
  { value: 'secure', label: 'Enhanced Security' },
  { value: 'scalable', label: 'Highly Scalable' },
  { value: 'offline', label: 'Offline Capabilities' },
  { value: 'template_lib', label: 'Template Library' },
  { value: 'robotics', label: 'Robotics & IoT Integration' },
  { value: 'autonomous', label: 'Autonomous Systems' },
  { value: 'creative_tools', label: 'Creative Generation Tools' },
  { value: 'trading_platform', label: 'Trading/Exchange Platform' },
  { value: 'virtual_avatar', label: 'Virtual Avatar/Presence' },
  { value: 'llm_integration', label: 'LLM/GenAI Integration' },
  { value: 'pos_integration', label: 'POS System Integration' },
  { value: 'menu_management', label: 'Menu Management' },
];

export const useCaseOptions = [
  { value: 'reporting', label: 'Reporting & Dashboards' },
  { value: 'automation', label: 'Workflow Automation' },
  { value: 'lead_gen', label: 'Lead Generation' },
  { value: 'customer_management', label: 'Customer Management' },
  { value: 'project_management', label: 'Project Management' },
  { value: 'inventory', label: 'Inventory Management' },
  { value: 'vendor_management', label: 'Vendor & Supplier Management' },
  { value: 'communication', label: 'Team Communication' },
  { value: 'scheduling', label: 'Scheduling & Calendar' },
  { value: 'billing', label: 'Billing & Invoicing' },
  { value: 'compliance', label: 'Compliance & Audit' },
  { value: 'monitoring', label: 'Monitoring & Alerts' },
  { value: 'customer_support', label: 'Customer Support' },
  { value: 'content_mgmt', label: 'Content Management' },
  { value: 'analytics', label: 'Data Analysis' },
  { value: 'integration', label: 'System Integration' },
  { value: 'form_builder', label: 'Form & Survey Builder' },
  { value: 'ai_assistant', label: 'AI Assistant' },
  { value: 'marketplace', label: 'Marketplace Platform' },
  { value: 'recruiting', label: 'Recruiting & Hiring' },
  { value: 'content_generation', label: 'Content Generation' },
  { value: 'virtual_presence', label: 'Virtual Communication & Presence' },
  { value: 'agent_automation', label: 'AI Agent Automation' },
];

export const categoryOptions = [
  { value: 'saas', label: 'SaaS' },
  { value: 'internal_tools', label: 'Internal Tools' },
  { value: 'sites', label: 'Websites' },
  { value: 'games', label: 'Games' },
  { value: 'ai_apps', label: 'AI Apps' },
];

export const templateTypes = [
  { value: 'altaner', label: 'Projects' },
  { value: 'workflow', label: 'Workflows' },
  { value: 'agent', label: 'Agents' },
];

export const sortOptions = [
  { value: 'featured', label: 'Featured' },
  { value: 'newest', label: 'Newest' },
  { value: 'name', label: 'Name' },
];
